### ISSUE TITLE
ex 14 db 값을 위한 설정 파일. 및 @Component 어노테이션

### ISSUE THREAD

**Issue by wsh096** [wsh096/jpa-study#7]
예제 14번을 기점으로 본격적으로 
DB에 값을 저장하는 방식으로 형태가 변경되었다.

이 중 설정 파일 부분 특히 .yml의 경우 들여쓰기와 띄어쓰기가 주요하다.
이 부분을 나는 잘 틀리니까 정리!
.yml 설정의 경우
`: `띄어쓰기를 해줘야 한다. 이렇게 안 하면 값을 인식을 못한다.
개인적으로 
.yml 과 .properties의 설정 파일을 바꿔주는 사이트가 유용해서
추천 https://mageddo.com/tools/yaml-converter
```
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: '0000'

  jpa:
    hibernate:
       ddl-auto: create-drop
    generate-ddl: true
    properties:
      format_sql: true
      hibernate:
        show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  mustache:
    suffix: .html

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
```

+ @Component 어노테이션의 활용.
이 어노테이션의 경우 
이전까지 내가 잘못 사용해 온 Entity를 private final 로 선언해온 것을
Bean을 주입해 사용해 오게 만들어 준 어노테이션이다.
하지만 해당 어노테이션 없이
값을 import 해 와서 반환하고 사용하는 방식을 활용하면
Bean의 주입이 없어도 된다.
그리고 final로 선언하게 되면 안 되는 결정적인 이유가
해당 값들은 계속 바뀌고 추가되고 해야되는 변용을 요구하는데
final로 선언되면 해당 값이 고정되는 문제가 있다는 걸,
실제 DB를 통해 확인했다.

즉 사용해서는 안 된다.

+ h2 console의 모습 일부 확인

![image](https://user-images.githubusercontent.com/61614348/235175559-7267ab26-8bc3-4558-acf5-e8a3b35d7fce.png)
